sprint-1/step-1 commit
FunChosa/react-burger pull request #1
Opened 2023-10-20 14:16 UTC by FunChosa

Pull request for sprint-1/step-1

2023-10-20 15:09 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- В компоненте App-header требуется поправить семантику, переделать div в ссылки. Иконка и текст должны быть обёрнуты в ссылку.

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь <https://learn.javascript.ru/coding-style>. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (<https://prettier.io/>)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-10-20 15:09 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  })),
**Надо исправить:**

Требуется полное описание структуры ингредиента, у вас указаны не все поля.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

**Надо исправить:**

Во многих компонентах будет дублироваться описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл `prop-types.js` в папке `utils`) и переиспользовать описание пропсов ингредиента, а не дублировать;

2023-10-20 15:09 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  };
**Надо исправить:**

Лучше вынести это в отдельный компонент, а не делать функции для рендера. Не забудьте про PropTypes.

2023-10-20 15:09 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }, {});
**Можно лучше:**

в будущем лучше обернуть в `useMemo`

2023-10-20 15:09 UTC, ArslanMustafin commented on src/components/app-header/app-header.jsx
> +function AppHeader() {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-10-20 15:09 UTC, ArslanMustafin commented on src/components/app-header/app-header.jsx
> +  const createNavigationItem = ({ icon, text, inactiveTextColor }) => {
**Надо исправить:**

Лучше вынести это в отдельный компонент, а не делать функции для рендера. Не забудьте про PropTypes.

2023-10-20 15:09 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +      </section>
**Надо исправить:**

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```
И уже использовать их в jsx))

2023-10-20 15:09 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  })),
**Надо исправить:**

Требуется полное описание структуры ингредиента, у вас указаны не все поля.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

**Надо исправить:**

Во многих компонентах будет дублироваться описание PropTypes ингредиента.
Следует вынести его в отдельный файл (можно создать файл `prop-types.js` в папке `utils`) и переиспользовать описание пропсов ингредиента, а не дублировать;

2023-10-20 15:09 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        <section className={style.box__container}>{renderItems(itemsByType.bun)}</section> { /* бокс с бувочками */ }
**Можно лучше:**

в идеале, вам лучше вынести этот блок в отдельный компонент, т.к. он повторяется. Назвать его можно `ingredinets-category`.

2023-10-20 17:35 UTC, FunChosa commented
Компонент App в данный момент находится в папке /src/components/app/. 
Он должен быть вынесен на уровень выше?

2023-10-20 18:06 UTC, ArslanMustafin commented
> Компонент App в данный момент находится в папке /src/components/app/. Он должен быть вынесен на уровень выше?

Нет, я по ошибке добавил, у вас всё правильно!))

2023-10-21 09:49 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличая работа. 🔥

### **Вы молодец! Приступайте к выполнению следующего этапа, не пугайтесь, работа не принята, чтобы была возможность отправить на проверку следующий этап.**

- Практически все замечания были исправлены;

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- Отметил замечания в коде.

2023-10-21 09:49 UTC, ArslanMustafin commented on src/components/app-header/create-navigation-item.jsx
> +function CreateNavigationItem({ icon, text, inactiveTextColor }) {
**Надо исправить:**

Это же компонент) поэтому называть надо существительными, например `NavigationItem`

2023-10-21 09:49 UTC, ArslanMustafin commented on src/components/burger-ingredients/render-items.jsx
> +function RenderItems({ items }) {
**Надо исправить:**

Это же компонент) поэтому называть надо существительными, например `BurgerIngredient`

2023-10-21 09:49 UTC, ArslanMustafin commented on src/components/burger-ingredients/render-items.jsx
> +    return (
**Надо исправить:**

Вывод по циклу перенесите в `ingredients-category`, а контент оставьте тут. Не забудьте убрать `key`, он нужен только если мы итерируем элемент.

2023-10-26 06:28 UTC, merged